- name: testing variable precedence
  hosts: localhost
  vars:
    NAME: Sivakumar-play
  tasks:
  - name: variable at tasks level
    vars:
      NAME: Sivakumar-task
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"