- name: create user
  hosts: localhost
  tasks:
  - name: check roboshop user exist or not
  # when you want to run linux commands directly i.e. in the case ansible module not available.
  # When user doesnot exists, ansible treating this failure and comout by default.
    ansible.builtin.command: id roboshop
    register: output # This output is variable name.
    ignore_errors: true

  - name: print the command output
    ansible.builtin.debug:
      msg: "output is: {{output}}"

  - name: print exit status
    ansible.builtin.debug:
      msg: "output is: {{output.rc}}"

  - name: create user roboshop
    become: yes # sudo for this taks only
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0