- name: simple condition
  hosts: localhost
  vars: 
    name: DevOps
  tasks:
  - name: run this if name is DevOps
    ansible.builtin.debug:
      msg: "Hello {{NAME}}"
    when: "{{NAME}}" == "DevOps"