- name: simple condition
  hosts: localhost
  vars:
    name: DevOps
  tasks:
    - name: run this if name is DevOps
      ansible.builtin.debug:
        msg: "Hello {{ name }}"
      when: name == "DevOps" # if this expression is true then only this module will run
